/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AnalysesRouteImport } from './routes/analyses'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as OperatorsIndexRouteImport } from './routes/operators.index'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'
import { Route as OperatorsOperatorIdRouteImport } from './routes/operators.$operatorId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysesRoute = AnalysesRouteImport.update({
  id: '/analyses',
  path: '/analyses',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsIndexRoute = OperatorsIndexRouteImport.update({
  id: '/operators/',
  path: '/operators/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsOperatorIdRoute = OperatorsOperatorIdRouteImport.update({
  id: '/operators/$operatorId',
  path: '/operators/$operatorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyses': typeof AnalysesRoute
  '/chat': typeof ChatRoute
  '/intake': typeof IntakeRoute
  '/settings': typeof SettingsRoute
  '/operators/$operatorId': typeof OperatorsOperatorIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/operators/': typeof OperatorsIndexRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyses': typeof AnalysesRoute
  '/chat': typeof ChatRoute
  '/intake': typeof IntakeRoute
  '/settings': typeof SettingsRoute
  '/operators/$operatorId': typeof OperatorsOperatorIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/operators': typeof OperatorsIndexRoute
  '/patients': typeof PatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyses': typeof AnalysesRoute
  '/chat': typeof ChatRoute
  '/intake': typeof IntakeRoute
  '/settings': typeof SettingsRoute
  '/operators/$operatorId': typeof OperatorsOperatorIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/operators/': typeof OperatorsIndexRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analyses'
    | '/chat'
    | '/intake'
    | '/settings'
    | '/operators/$operatorId'
    | '/patients/$patientId'
    | '/operators/'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analyses'
    | '/chat'
    | '/intake'
    | '/settings'
    | '/operators/$operatorId'
    | '/patients/$patientId'
    | '/operators'
    | '/patients'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analyses'
    | '/chat'
    | '/intake'
    | '/settings'
    | '/operators/$operatorId'
    | '/patients/$patientId'
    | '/operators/'
    | '/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalysesRoute: typeof AnalysesRoute
  ChatRoute: typeof ChatRoute
  IntakeRoute: typeof IntakeRoute
  SettingsRoute: typeof SettingsRoute
  OperatorsOperatorIdRoute: typeof OperatorsOperatorIdRoute
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
  OperatorsIndexRoute: typeof OperatorsIndexRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyses': {
      id: '/analyses'
      path: '/analyses'
      fullPath: '/analyses'
      preLoaderRoute: typeof AnalysesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators/': {
      id: '/operators/'
      path: '/operators'
      fullPath: '/operators/'
      preLoaderRoute: typeof OperatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators/$operatorId': {
      id: '/operators/$operatorId'
      path: '/operators/$operatorId'
      fullPath: '/operators/$operatorId'
      preLoaderRoute: typeof OperatorsOperatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalysesRoute: AnalysesRoute,
  ChatRoute: ChatRoute,
  IntakeRoute: IntakeRoute,
  SettingsRoute: SettingsRoute,
  OperatorsOperatorIdRoute: OperatorsOperatorIdRoute,
  PatientsPatientIdRoute: PatientsPatientIdRoute,
  OperatorsIndexRoute: OperatorsIndexRoute,
  PatientsIndexRoute: PatientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
