"""Add pricing rules

Revision ID: 340c7bc3b7f8
Revises: 20260326_0003
Create Date: 2026-03-30 02:08:09.540821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '340c7bc3b7f8'
down_revision: Union[str, Sequence[str], None] = '20260326_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_catalog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('coefficient', sa.Integer(), nullable=False),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_catalog_code'), 'analysis_catalog', ['code'], unique=True)
    op.create_table('pricing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Enum('conventionnel', 'non_conventionnel', name='pricing_tier_enum'), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier')
    )
    op.add_column('analysis_requests', sa.Column('pricing_tier', sa.Enum('conventionnel', 'non_conventionnel', name='pricing_tier_enum'), server_default='non_conventionnel', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_requests', 'pricing_tier')
    op.drop_table('pricing_rules')
    op.drop_index(op.f('ix_analysis_catalog_code'), table_name='analysis_catalog')
    op.drop_table('analysis_catalog')
    # ### end Alembic commands ###
