"""Add LabResult model

Revision ID: 843ff2bd9b06
Revises: 340c7bc3b7f8
Create Date: 2026-03-30 14:56:36.347022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '843ff2bd9b06'
down_revision: Union[str, Sequence[str], None] = '340c7bc3b7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_request_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending_validation', 'approved', 'rejected', 'delivered', name='result_status_enum'), server_default='pending_validation', nullable=False),
    sa.Column('operator_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_request_id'], ['analysis_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_request_id')
    )
    op.create_table('result_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lab_result_id', sa.UUID(), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lab_result_id'], ['lab_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operator_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result_audit_logs')
    op.drop_table('lab_results')
    # ### end Alembic commands ###
